coverage:
  range: "85...100"
  status:
    project:
      default:
        target: 85
        threshold: 10%
    patch:
      default:
        target: 90
        threshold: 10%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
