coverage:
  range: "85...100"
  status:
    project:
      default:
        target: 80
        threshold: 10%
    patch: off

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
