apiVersion: v1
kind: Service
metadata:
  name: sf-backend-svc
spec:
  type: ClusterIP
  selector:
    app: sf-backend
  ports:
  - port: 3000
    targetPort: 3000
    name: api-port
  - port: 1935
    targetPort: 1935
    name: rtmp-port
  - port: 8080
    targetPort: 8080
    name: http-streaming-port
