version: 2.1

jobs:
  node-checkout:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
        name: Install Dependencies
        command: |
          yarn
          npx lerna bootstrap
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  build:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - run:
        name: Build Packages
        command: yarn build

  lint:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      - run:
        name: Lint Packages
        command: yarn lint

  test:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      run:
        name: Test Backend
        command: cd packages/backend && yarn test:cov

  test-e2e:
    working_directory: ~/skillfuze
    docker:
      - image: circleci/node:lts
    steps:
      run:
        name: Test Backend E2E
        command: cd packages/backend && yarn test:e2e

workflows:
  build-and-test:
    jobs:
      - node-checkout
      - build:
        - requires:
          - node-checkout
      - lint:
        - requires:
          - build
      - test:
        - requires:
          - build
      - test-e2e:
        - requires:
          - test
